version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: checkin_postgres
    environment:
      POSTGRES_DB: checkin_db
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: 1234teste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - checkin-net

  backend:
    build: ./Back-end
    container_name: checkin_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/checkin_db
      SPRING_DATASOURCE_USERNAME: teste
      SPRING_DATASOURCE_PASSWORD: 1234teste
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - checkin-net

  frontend:
    build: ./Front-end
    container_name: checkin_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - checkin-net

networks:
  checkin-net:

volumes:
  pgdata: